/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import conectaBanco.ModeloTabela;
import fotos_JinternalFrame.HighScoreInternalFrame;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
//import static org.eclipse.persistence.jpa.jpql.parser.Expression.SQL;

/**
 *
 * @author Manoel Henrique
 */
public class HighScore extends javax.swing.JFrame {
    String jogadores = "";
    conectaBanco.Conexao Conecta = new conectaBanco.Conexao();
    
    public HighScore() {
        initComponents();  
        try {
            telaFundo.add(pontuacao);
            pontuacao.setVisible(true);
            pontuacao.setMaximum(true);
        } catch (Exception e) {
        }
        Conecta.conecta();
        preencherTabela("select nome, pontuacao from pontos");
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoMinadoPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory(null).createEntityManager();
        pontosQuery = java.beans.Beans.isDesignTime() ? null : campoMinadoPUEntityManager.createQuery("SELECT p FROM Pontos p");
        pontosList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : pontosQuery.getResultList();
        telaFundo = new javax.swing.JDesktopPane();
        pontos = new javax.swing.JLabel();
        jogarN = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Campo Minado - High Score");
        setResizable(false);

        telaFundo.setBackground(new java.awt.Color(255, 255, 255));

        pontos.setFont(new java.awt.Font("Tahoma", 3, 22)); // NOI18N
        pontos.setForeground(new java.awt.Color(242, 156, 24));
        pontos.setText("High Score");

        jogarN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jogarN.setForeground(new java.awt.Color(242, 156, 24));
        jogarN.setText("Jogar Novamente");
        jogarN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogarNActionPerformed(evt);
            }
        });

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable);

        telaFundo.setLayer(pontos, javax.swing.JLayeredPane.PALETTE_LAYER);
        telaFundo.setLayer(jogarN, javax.swing.JLayeredPane.PALETTE_LAYER);
        telaFundo.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout telaFundoLayout = new javax.swing.GroupLayout(telaFundo);
        telaFundo.setLayout(telaFundoLayout);
        telaFundoLayout.setHorizontalGroup(
            telaFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaFundoLayout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addGroup(telaFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaFundoLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaFundoLayout.createSequentialGroup()
                        .addGap(0, 75, Short.MAX_VALUE)
                        .addGroup(telaFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaFundoLayout.createSequentialGroup()
                                .addComponent(pontos)
                                .addGap(222, 222, 222))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaFundoLayout.createSequentialGroup()
                                .addComponent(jogarN)
                                .addGap(183, 183, 183))))))
        );
        telaFundoLayout.setVerticalGroup(
            telaFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pontos)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jogarN)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaFundo)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaFundo)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jogarNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jogarNActionPerformed
        this.dispose();
        TelaInicial a = new TelaInicial();
        a.setVisible(true);
        
        
    }//GEN-LAST:event_jogarNActionPerformed

    public void preencherTabela(String SQL){
        ArrayList dados = new ArrayList();
        
        String [] Colunas = new String[]{"nome", "pontuacao"};
    
       Conecta.executaSQL(SQL);
       
        try {
            Conecta.rs.first();
            do{
              dados.add(new Object[]{Conecta.rs.getString("nome"),Conecta.rs.getInt("pontuacao")});
            }while(Conecta.rs.next());
        } catch (SQLException ex) {
            Logger.getLogger(HighScore.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Erro"+ex);
        }    
       ModeloTabela modelo = new ModeloTabela(dados, Colunas);
    jTable.setModel(modelo);
       jTable.getColumnModel().getColumn(0).setPreferredWidth(180);
       jTable.getColumnModel().getColumn(0).setResizable(false);
       jTable.getColumnModel().getColumn(1).setPreferredWidth(80);
       jTable.getColumnModel().getColumn(1).setResizable(false);
       jTable.getTableHeader().setReorderingAllowed(false);
       jTable.setAutoResizeMode(jTable.AUTO_RESIZE_OFF);
       jTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION); 

    }  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HighScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HighScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HighScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HighScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HighScore().setVisible(true);
            }
        });
    }
   // private conectaBanco.Conexao Conecta = new conectaBanco.Conexao();
    private HighScoreInternalFrame pontuacao = new HighScoreInternalFrame();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager campoMinadoPUEntityManager;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable;
    private javax.swing.JButton jogarN;
    private javax.swing.JLabel pontos;
    private java.util.List<telas.Pontos> pontosList;
    private javax.persistence.Query pontosQuery;
    private javax.swing.JDesktopPane telaFundo;
    // End of variables declaration//GEN-END:variables
}
